commands:
  - commands/**/*

util:
  - utils/**/*
  - util.ts

config:
  - .vscode/**/*
  - .github/**/*
  - package.json
  - .editorconfig
  - .gitignore
  - tsconfig.json
  - watch.json
  - .eslintrc

core:
  - index.ts

messages:
  - messages.ts
  
events:
  - events/**/*

docs:
  - docs/**/*
  - README.md
  - .env.example
