commands:
  - commands/**/*.ts

util:
  - utils/**/*

config:
  - .vscode/**/*
  - .github/**/*
  - package.json
  - .editorconfig
  - .gitignore
  - tsconfig.json
  - watch.json
  - .eslintrc

init:
  - init.ts

messages:
  - messages.ts
  
events:
  - events/**/*

docs:
  - docs/**/*
  - *.md
  - .env.example
