commands:
  - commands/**/*.ts

util:
  - utils/**/*

config:
  - .vscode/**/* # visual studio code config
  - .github/**/* # how meta
  - package.json # name and stuff
  - .editorconfig
  - .gitignore # private
  - tsconfig.json # compiler config
  - watch.json # glitch hosting

init:
  - init.ts

messages:
  - messages.ts
  
events:
  - events/**/*

docs:
  - docs/**/*
  - *.md
  - .env.example
