commands:
  - commands/**/*

modules:
  - utils/**/*
  - util.ts

config:
  - .vscode/**/*
  - package.json
  - .editorconfig
  - .gitignore
  - tsconfig.json
  - watch.json

core:
  - index.ts
  - thisfileisonlyinheresoitdoesnotbreak.ts
messages:
  - messages.ts
  
events:
  - events/**/*
